#!/bin/bash

function generate_csv {
dir="matrix/data/$1"
res="results/matrix_$1.csv"
echo nx ny nz time[sec]| sed 's/ /,/g' > $res
for grid in $dir/*
do
    name=$(basename $grid)
    nx=$(echo $name | cut -d '_' -f 1)
    ny=$(echo $name | cut -d '_' -f 2)
    nz=$(echo $name | cut -d '_' -f 3)
    vals=$(cat $grid/* | grep Communication | awk '{print $3}')
    avg=$(echo $vals | awk '{print ($1+$2+$3+$4+$5+$6+$7+$8+$9+$10)/10}')
    echo $nx $ny $nz $avg | sed 's/ /,/g' >> $res
done
}

generate_csv 800
generate_csv 1200
generate_csv 2400