#!/bin/bash

for file in $1/* $2/*
do
    nproc=$(basename ${file} | cut -d '_' -f 1)
    level=$(basename ${file} | cut -d '_' -f 2)
    type=$(basename ${file} | cut -d '_' -f 3)
    grid=$(cat $file | grep 'Process grid' | awk '{$1=$1}; {printf("%d %d %d\n",$5,$6,$7)}')

    if [ "${level}" == 'single' ]
    then binding='core'
    elif [ "${level}" == 'double' ]
    then binding='socket'
    else binding='node'
    fi

    name="${type}_${binding}_${nproc}"
    resfile="upload/${name}.csv"

    echo "# Number of processors: ${nproc}" > ${resfile}
    echo "# Process binding: ${binding}" >> ${resfile}
    echo "# Process grid: ${grid}" >> ${resfile}
    echo "maxtime,mintime,jacobima,jacobimi,mlups" >> ${resfile}

    cat ${file} | grep Maxtime | awk '{$1=$1};1' | sed 's/ , /,/g' | \
    sed 's/ + /,/g' | awk '{printf("%lf,%lf,%lf,%lf,%lf\n",$3,$4,$6,$5,$10)}' >> ${resfile}

done