#!/bin/bash

data=../section2/results/pp_table.csv
echo 'type,comm_level,lat[usec],bw[GB/s]' > results/network_data.csv
cat $data | grep ucx | sed 's/,/ /g' | awk '\
NR==1 {printf "thin,core,%s,%s\n",$3,$4; printf "gpu,core,%s,%s\n",$5,$6}; \
NR==2 {printf "thin,socket,%s,%s\n",$3,$4; printf "gpu,socket,%s,%s\n",$5,$6}; \
NR==3 {printf "thin,node,%s,%s\n",$3,$4; printf "gpu,node,%s,%s\n",$5,$6}; ' >> results/network_data.csv
